Lj 24 layout -  Draft  Work in progress
DTS-STN/Life-Journeys pull request #10
Opened 2021-04-09 19:21 UTC by MarcoGoC

# Description

[LJ-24] changes are getting too big splitting the changes in two PR 

 Added basic barebone language translation 
 Added Meta, Header, Footer from React based Prototype project
 Updated the components to work with Next 
 Updated links and translations

## Test Instructions

1. grab the branch 
1. do npm i 
1. npm start dev
1. check the browser

## Meets Definition of Done

- [ ] TODO: Fonts, margins, canada logo, change label to 'english' after translation along with gov logo

[LJ-24]: https://lj-decd.atlassian.net/browse/LJ-24

2021-04-09 19:26 UTC, P0NDER0SA approved these changes
This looks pretty clean @MarcoGoC .  I'm going to add the parameter to --passWithNoTests to pass this until we actually write a test :)

2021-04-12 12:50 UTC, pcraig3 requested changes
There’s quite a few issues to fix up here.

I’ve commented about most of them, but there are probably more things that will come up.

Mostly though we should avoid ~1000 line PRs like this. There are multiple stories being addressed in this PR and it will probably get bigger rather than smaller. It would have been better to split this into multiple PRs — eg, doing the header first, and the footer later, and then the translations afterwards. 

It’s really hard to review PRs like this and it will make it harder for others to do PRs alongside it as there is a large possibility of conflicts later on.

2021-04-12 14:07 UTC, MarcoGoC commented on components/atoms/ActionButton.js
> +export function ActionButton(props) {
yes, actually the alpha site took it from the prototype

2021-04-13 13:12 UTC, MarcoGoC commented
Branch wont be updated 
Leaving here for comments

2021-04-21 19:43 UTC, closed without merging