Lj 266 card component
DTS-STN/Life-Journeys pull request #69
Opened 2021-07-13 15:35 UTC by MarcoGoC

# Description

[LJ-266] Card Component 

Added the new Card component (based on the topicbox) changes to the page to make it look like 
the new prototype page

## Test Instructions

1. Download the branch and run 

## Meets Definition of Done

- [ ] Meets design spec
- [ ] unit tests are included

2021-07-13 15:47 UTC, P0NDER0SA commented
A couple things i noticed... when i ran it i see this warning for the card:
![image](https://user-images.githubusercontent.com/32133001/125483253-855469a9-714a-4eea-8ed2-8f771c276789.png)

I'm wondering if we couldn't adjust the border as well (maybe remove it) to sharpen the look a bit -- and there are a couple of code recommendations (unused imports, etc) that the LGTM bot mentions above.  These are all very very minor though - so up to you if you want to push and fix these as a separate item.

2021-07-13 17:22 UTC, krischarbonneau commented on components/atoms/Card.js
> +      <div className="">
can probably remove the className portion of this since it's empty

2021-07-13 17:27 UTC, krischarbonneau requested changes
I think this looks good for the most part, looking at the figma designs though there is far too much padding between the title and the service. I think we should make the service more of a subtitle like the designs.
![Screenshot 2021-07-13 131834](https://user-images.githubusercontent.com/71025360/125498100-460d0670-6c2b-463f-a251-acbefba91fdb.png)
![Screenshot 2021-07-13 131817](https://user-images.githubusercontent.com/71025360/125498108-5d4062bf-82f9-487e-8e64-d50b753d67c2.png)

2021-07-13 17:58 UTC, P0NDER0SA approved these changes
My stuff was addressed!  Looks good... just check out Kris' stuff now i guess

2021-07-13 19:04 UTC, merged

2021-07-14 01:11 UTC, MarcoGoC commented
> I think this looks good for the most part, looking at the figma designs though there is far too much padding between the title and the service. I think we should make the service more of a subtitle like the designs.
> ![Screenshot 2021-07-13 131834](https://user-images.githubusercontent.com/71025360/125498100-460d0670-6c2b-463f-a251-acbefba91fdb.png)
> ![Screenshot 2021-07-13 131817](https://user-images.githubusercontent.com/71025360/125498108-5d4062bf-82f9-487e-8e64-d50b753d67c2.png)

Problem is that the cards look swirly (up and down) when the title is in two lines that pushes the links down and all the cards are  uneven. I'll try something else hopefully it wont look as bad